/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppViolationsRouteImport } from './routes/_app.violations'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMyRoomRouteImport } from './routes/_app.my-room'
import { Route as AppMetersRouteImport } from './routes/_app.meters'
import { Route as AppMaintenanceNewRouteImport } from './routes/_app.maintenance-new'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppDepositsRouteImport } from './routes/_app.deposits'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppViolationsRoute = AppViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyRoomRoute = AppMyRoomRouteImport.update({
  id: '/my-room',
  path: '/my-room',
  getParentRoute: () => AppRoute,
} as any)
const AppMetersRoute = AppMetersRouteImport.update({
  id: '/meters',
  path: '/meters',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceNewRoute = AppMaintenanceNewRouteImport.update({
  id: '/maintenance-new',
  path: '/maintenance-new',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositsRoute = AppDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof AppApplicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deposits': typeof AppDepositsRoute
  '/invoices': typeof AppInvoicesRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/maintenance-new': typeof AppMaintenanceNewRoute
  '/meters': typeof AppMetersRoute
  '/my-room': typeof AppMyRoomRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/rooms': typeof AppRoomsRoute
  '/violations': typeof AppViolationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof AppApplicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deposits': typeof AppDepositsRoute
  '/invoices': typeof AppInvoicesRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/maintenance-new': typeof AppMaintenanceNewRoute
  '/meters': typeof AppMetersRoute
  '/my-room': typeof AppMyRoomRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/rooms': typeof AppRoomsRoute
  '/violations': typeof AppViolationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deposits': typeof AppDepositsRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/maintenance-new': typeof AppMaintenanceNewRoute
  '/_app/meters': typeof AppMetersRoute
  '/_app/my-room': typeof AppMyRoomRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/violations': typeof AppViolationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/deposits'
    | '/invoices'
    | '/maintenance'
    | '/maintenance-new'
    | '/meters'
    | '/my-room'
    | '/notifications'
    | '/reports'
    | '/rooms'
    | '/violations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/deposits'
    | '/invoices'
    | '/maintenance'
    | '/maintenance-new'
    | '/meters'
    | '/my-room'
    | '/notifications'
    | '/reports'
    | '/rooms'
    | '/violations'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/applications'
    | '/_app/dashboard'
    | '/_app/deposits'
    | '/_app/invoices'
    | '/_app/maintenance'
    | '/_app/maintenance-new'
    | '/_app/meters'
    | '/_app/my-room'
    | '/_app/notifications'
    | '/_app/reports'
    | '/_app/rooms'
    | '/_app/violations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/violations': {
      id: '/_app/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof AppViolationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-room': {
      id: '/_app/my-room'
      path: '/my-room'
      fullPath: '/my-room'
      preLoaderRoute: typeof AppMyRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meters': {
      id: '/_app/meters'
      path: '/meters'
      fullPath: '/meters'
      preLoaderRoute: typeof AppMetersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance-new': {
      id: '/_app/maintenance-new'
      path: '/maintenance-new'
      fullPath: '/maintenance-new'
      preLoaderRoute: typeof AppMaintenanceNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposits': {
      id: '/_app/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof AppDepositsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepositsRoute: typeof AppDepositsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppMaintenanceNewRoute: typeof AppMaintenanceNewRoute
  AppMetersRoute: typeof AppMetersRoute
  AppMyRoomRoute: typeof AppMyRoomRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppViolationsRoute: typeof AppViolationsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepositsRoute: AppDepositsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppMaintenanceNewRoute: AppMaintenanceNewRoute,
  AppMetersRoute: AppMetersRoute,
  AppMyRoomRoute: AppMyRoomRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppViolationsRoute: AppViolationsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
